### ISSUE TITLE
TODO list for libtpms v0.10

### ISSUE THREAD

**Issue by stefanberger** [stefanberger/libtpms#431]
- [] Merge all outstanding rev180/183 changes:
  - [] deferred: https://github.com/stefanberger/libtpms/pull/395
  - [] deferred https://github.com/stefanberger/libtpms/commits/stefanberger/rev180.part3/
  - [X] https://github.com/stefanberger/libtpms/pull/439
- [X] deferred: ~~Support for RuntimeAttributes as used for support of FIPS: https://github.com/stefanberger/libtpms/pull/428~~
- [X] KDFe support via OpenSSL: https://github.com/stefanberger/libtpms/pull/424
- ~~[] KDFa support via OpenSSL: unlikely to work~~
- [X] Determine whether CrypEccEncrypt/Decrypt can be implemented with OpenSSL functions: no know API
- [X] Check that algorithm and command filtering is done where necessary
- [X] No: Enable SvnLimited and FirmwareLimited hierarchies? What would libtpms need to enable these?
  - No to FirmwareLimited: different versions of compilers compiling the same code may lead to different binaries and therefore measuring the libtpms binary may lead to different measurements even if the source is the same -- what should the firmware hash then be?
  - Deferring Svn-Limited hierarchy support to libtpms v0.11: https://github.com/stefanberger/libtpms/pull/470
- [] FIPS-compliance: Support [FIPS-140-3](https://trustedcomputinggroup.org/wp-content/uploads/TCG-FIPS-140-3-Guidance-for-TPM-2.0-Version-1.0-Revision-2_pub-1.pdf) guidance document? How?
   - [X] Easy to support:
     - Disablement of algorithms (ecdaa, ecschnorr) and curves (ecc-bn, ecc-bn-p*, ecc-sm2-p*)
     - Min. RSA key size: rsa-min-size=2048
     - Min. EC key suze: ecc-min-size=224
     - HMAC min. key size 112 bits : are there any keys smaller than 128bits when only AES symmetric crypto is supported?
     - ECC and RSA signature **generation** not allowed with SHA1: see code in FIPS 140 branch
   - Others:
     - Does preventing ECC key derivation solve the problem of prohibiting ECDSA signatures with derived ECC keys?
     - [X] Pair-wise consistency tests for RSA
   - Missing:
     - SHA1 etc. are used for HMAC testing but not tested on their own
     - XOR usage described in 5.5
     - See table 39 of FIPS 140-3 guidance document
 
For v0.11:
- SVN-limited hierarchy support: https://github.com/stefanberger/libtpms/pull/470
